### ISSUE TITLE
[Concepts Page - Section Headers]

### ISSUE THREAD

**Issue by yatil** [w3c/wai-mobile-intro#12]
The headings per se are not the problem of this page. While they are a bit vague, I think the content of the page can be streamlined a lot, removing the need for so many headings. 

* > If you’re used to developing in a desktop environment, or on a mobile environment without thinking much about accessibility, you’ve come to the right place to learn about making mobile devices accessible. First, some essential background.
  
  This is just a filler paragraph and we don’t need it. Same with the “What’s mobile?” heading – this is what this page is talking about.

* Everything under ”What’s mobile” could be easier to parse as a list with highlighted (bold) key terms.

* The “How is mobile different than desktop?” is very lengthy. If the what’s mobile section is good, this should not be needed. I also don’t see the relationship to accessibility clearly in the descriptions. Why is it harder/different to make a site or app accessible when the screen is smaller or there is touch input?

* “Merging input methods” and “Merging development techniques” are a bit weird as headings (merging with what?). I think they could go without the word “Merging”.

  I think both sections can be much shorter.

* “Mobile is part of a continuum” ➡️ “One website for all devices”

  Parts of this sections are repetetive with the sections before.

* “Why mobile is important” should be “Why mobile accessibility is important”

  I don’t think we have to make the case for general mobile use cases. No one doubts them. Let’s concetrate on the accessibility aspects.

* I’d like a bit more context to the individual resources on the bottom of the page, just listing (external) links is probably not too useful.

**Comment by kakinney** [comment]
+1 to Eric's assessment of the page.

**Comment by bakkenb** [comment]
I had the same opinion as Eric about the amount of headers. There are too many. It starts out good with logical questions as headers, then the headers become a bit overwhelming and hard to understand. I found that I had to read what the content was below the header, to understand what the header meant. Wondering if some of these could be combined as well.

**Comment by sharronrush** [comment]
I had written a detailed analysis but found it so much aligned to Eric's views that I think it simpler to just support that. Much of the page content is repetitive and unnecessary. Quite a bit of tersification is needed. 
- "Merging" is confusing as a heading term
- the questions as headers "How is Mobile Different/the Same" is a bit misleading since we want to entirely dispel the notion that there are "separate" requirements and so the points should be folded into a conceptual framework that does *not* separate them at all but strengthens to notion of the continuum. 
- Mini- personas are very good but would be much better placed in context of the issue
